// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://drwroajryewerflpjvin.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRyd3JvYWpyeWV3ZXJmbHBqdmluIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5NjE1MTAsImV4cCI6MjA3NDUzNzUxMH0.HFmgacdDdgdmR0JMLZi2zPJaDqK8BdwG07UXSoqRmV8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});